#!/bin/sh /etc/rc.common                                                        
                                                                                
START=99                                                                        
STOP=99                                                                      
                                                                                                                                                                
start() {                                                                       
	/usr/bin/wifi_monitor
}

stop() {
	kill -9 `pidof wifi_monitor`
}    
